inner_air/user/routes.py
import datetime
import os
import uuid

from flask import Blueprint, render_template, flash, redirect, url_for, request, abort
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.utils import secure_filename

from inner_air import db, app
from inner_air.models import User
from inner_air.user.forms import LoginForm, RegistrationForm, ForgotForm, ChangePasswordForm, ProfileForm, EmailForm, \
    SecurityAndAuthForm
from inner_air.user.token import generate_confirmation_token, confirm_token
from inner_air.utils.decorators import logout_required, check_confirmed
from inner_air.utils.email import send_email

user_bp = Blueprint(
    'user', __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/%s' % __name__
)


@user_bp.route('/login', methods=['GET', 'POST'])
@logout_required
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.query(User).filter_by(email=form.email.data).first()
        if user and user.verify_password(attempted_password=form.password.data):
            login_user(user)
            user.updateLastLogin()
            db.session.commit()
            if user.is_confirmed:
                flash(f'Success! You are logged in as: {user.firstname}', category='success')

            if user.is_admin:
                return redirect(url_for('admin.admin'))
            return redirect(url_for('profile.profile'))
        else:
            flash('You have entered an invalid email address or password.', category='danger')
    return render_template('user/login.html', form=form)


@user_bp.route('/register', methods=['GET', 'POST'])
@logout_required
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(
            firstname=form.firstname.data,
            email=form.email.data,
            password=form.password.data,
            is_confirmed=False
        )

        if db.session.query(User).filter_by(email=form.email.data).first() is None:
            db.session.add(user)
            user.updateLastLogin()
            db.session.commit()

            token = generate_confirmation_token(user.email)
            confirm_url = url_for('user.confirm_email', token=token, _external=True)
            html = render_template('user/confirm_email.html', confirm_url=confirm_url)
            subject = 'Please confirm your email'
            send_email(user.email, subject, html)

            login_user(user)
            flash('A confirmation email has been sent via email.', category='success')
            return redirect(url_for('user.unconfirmed'))
        else:
            flash('This email already exists. Try logging in, or register with a different email', category='danger')
    return render_template('user/register.html', form=form)


@user_bp.route('/confirm/<token>')
@login_required
def confirm_email(token):
    if current_user.is_confirmed:
        flash('Account already confirmed.', category='success')
        return redirect(url_for('main.home'))
    email = confirm_token(token)
    user = db.session.query(User).filter_by(email=current_user.email).first_or_404()
    if user.email == email:
        user.is_confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', category='success')
    else:
        flash('The confirmation link is invalid or has expired.', category='danger')
    return redirect(url_for('main.home'))


@user_bp.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.is_confirmed:
        return redirect(url_for('main.home'))
    return render_template('user/unconfirmed.html')


@user_bp.route('/resend')
@login_required
def resend_confirmation():
    if current_user.is_confirmed:
        flash('Your account has already been confirmed.', category='success')
        return redirect(url_for('main.home'))
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    html = render_template('user/confirm_email.html', confirm_url=confirm_url)
    subject = 'Please confirm your email'
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', category='success')
    return redirect(url_for('user.unconfirmed'))


@user_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('you\'ve been logged out', category='info')
    return redirect(url_for('main.home'))


@user_bp.route('/forgot', methods=['GET', 'POST'])
@logout_required
def forgot():
    form = ForgotForm()

    if form.validate_on_submit():
        user = db.session.query(User).filter_by(email=form.email.data).first()
        if user is not None:
            token = generate_confirmation_token(user.email)
            user.password_reset_token = token
            db.session.commit()

            reset_url = url_for('user.reset_password', token=token, _external=True)
            html = render_template('user/reset_request.html', email=user.email, reset_url=reset_url)
            subject = 'Reset your password'
            send_email(user.email, subject, html)
            return render_template('user/confirm_reset_request.html', email=user.email)
        else:
            flash('This email is not registered', category='danger')
    return render_template('user/forgot.html', form=form)


@user_bp.route('/forgot/<token>', methods=['GET', 'POST'])
@logout_required
def reset_password(token):
    email = confirm_token(token)
    user = db.session.query(User).filter_by(email=email).first_or_404()

    if user.password_reset_token is not None:
        form = ChangePasswordForm()
        if form.validate_on_submit():
            user = db.session.query(User).filter_by(email=email).first()
            if user:
                user.password = form.password.data
                user.password_reset_token = None
                db.session.commit()

                flash('Password changed successfully.', category='success')
                return redirect(url_for('main.home'))
            else:
                flash('Password change was unsuccessful.', category='danger')
                return redirect(url_for('main.home'))
        else:
            flash('You can now change your password.', category='success')
            return render_template('user/reset_password.html', form=form)
    else:
        flash('Can not reset the password, try again.', category='danger')
    return redirect(url_for('main.home'))


"""""
    update user profile
"""""


@user_bp.route('/settings/profile/<int:id>', methods=['GET', 'POST'])
@login_required
def profile(id):
    form = ProfileForm()
    user_profile = db.session.query(User).get_or_404(id)

    if user_profile.is_authenticated and current_user.is_admin:
        print('is admin')
    elif user_profile.is_authenticated and not current_user.is_admin:
        if user_profile != current_user:
            abort(403)
    if user_profile.is_authenticated:
        form.anonymous_mode.checked = user_profile.is_anonymous

    if form.validate_on_submit():

        user_profile.firstname = request.form['firstname']
        print(form.anonymous_mode.data)
        user_profile.is_anonymous = form.anonymous_mode.data

        if request.files['profile_picture']:
            user_profile.profile_picture = request.files['profile_picture']

            picture_fname = secure_filename(user_profile.profile_picture.filename)
            picture_name = '-'.join([str(uuid.uuid4()), str(picture_fname)])
            user_profile.profile_picture.save(os.path.join(app.config['UPLOAD_FOLDER'], picture_name))
            user_profile.profile_picture = picture_name
            try:
                db.session.commit()
                flash('Your profile has been updated successfully.', category='success')
                return render_template('user/profile.html', form=form, user_profile=user_profile)
            except Exception:
                flash('An error occurred...try again.', category='danger')
                return render_template('user/profile.html', form=form, user_profile=user_profile)
        else:
            db.session.commit()
            flash('Your profile has been updated successfully.', category='success')
            form.anonymous_mode.checked = user_profile.is_anonymous

            return render_template('user/profile.html', form=form, user_profile=user_profile)
    else:
        return render_template('user/profile.html', form=form, user_profile=user_profile)


@user_bp.route('/settings/emails/<int:id>', methods=['GET', 'POST'])
@login_required
@check_confirmed
def emails(id):
    form = EmailForm()
    user_email = db.session.query(User).get_or_404(id)

    if user_email.is_authenticated and current_user.is_admin:
        print('is admin')
    elif user_email.is_authenticated and not current_user.is_admin:
        if user_email != current_user:
            abort(403)

    if form.validate_on_submit():
        user_email.email = request.form['email']

        if current_user.is_admin:
            user_email.is_confirmed = True
        else:
            user_email.is_confirmed = False

        try:
            db.session.commit()
            token = generate_confirmation_token(user_email.email)
            confirm_url = url_for('user.confirm_email', token=token, _external=True)
            html = render_template('user/confirm_email.html', confirm_url=confirm_url)
            subject = 'Please confirm your email'
            send_email(user_email.email, subject, html)

            flash('Your email has been updated successfully.', category='success')
            return render_template('user/email_settings.html', form=form, user_email=user_email)
        except Exception:
            flash('An error occurred...try again.', category='danger')

inner_air/user/templates/user/account_security.html
{% extends 'base.html' %}
{% block title %} Account Security {% endblock %}
{% block content %}

<!-- CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{{ url_for('.static', filename='css/form-validity.css') }}">
<link rel="stylesheet" href="{{ url_for('user.static', filename='css/user.css') }}">

<!--  JS  -->
<script defer src="{{ url_for('.static', filename='js/password-validity.js') }}"></script>
<script defer src="{{ url_for('.static', filename='js/confirm-password-validity.js') }}"></script>

{% include 'includes/sidebar.html' %}
<div>
    <form method="POST" action="" class="form-register">
        {{ form.hidden_tag() }}

        <fieldset>
            <legend>Change Password</legend>
            <div class="form-container">
                <!-- New Password input -->
                <div class="form-section">
                    {{ form.password.label(class='form-label') }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password }}
                    {% endif %}
                </div>
                <!-- indicator -->
				<div class="indicator">
					<span class="password-validity-weak"></span>
					<span class="password-validity-medium"></span>
					<span class="password-validity-strong"></span>
				</div>
				<span class="password-validity-summary"></span>

                <!-- Confirm New password input -->
                <div class="form-section">
                    {{ form.confirm_password.label(class='form-label') }}
                    {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.confirm_password }}
                    {% endif %}
                </div>
                <span class="cpassword-validity-summary"></span>

            </div>
        </fieldset>
        {{ form.submit(class="button--blue") }}
    </form>
</div>

{% endblock %}

inner_air/user/templates/user/confirm_email.html
<p>
    Welcome! Thanks for signing up. Please follow this link to activate your account:
</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

inner_air/user/templates/user/confirm_reset_request.html
{% extends 'base.html' %}
{% block title %}
    Forgot you password
{% endblock %}
{% block content %}

    <link rel="stylesheet" href="{{ url_for('user.static', filename='css/user.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script defer src="{{ url_for('.static', filename='js/app.js')}}"></script>

    <div id='modal-2' class='modal'>
        <div class='modal-content'>
            <!-- Modal header -->
            <div class="modal-header">
                   <i class="fa fa-envelope-o circle"></i>
            </div>
            <h2>Check your email</h2>
            <!-- Modal body -->
            <div class="modal-body br">
                <p>
                    <span>We sent a password reset link to</span>
                    <span>{{ email }}</span>
                </p>
            </div>
            <hr>
            <!-- Modal footer -->
            <div class="modal-footer">
                <p>
                    <a class="button--dynamic" href="{{ url_for('user.login') }}"><span>&#8592;</span> return to sign in</a>
                </p>
            </div>
        </div>
    </div>

{% endblock %}

inner_air/user/templates/user/email_settings.html
{% extends 'base.html' %}
{% block title %} Email Settings {% endblock %}
{% block content %}

<!-- CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{{ url_for('user.static', filename='css/user.css') }}">
<link rel="stylesheet" href="{{ url_for('.static', filename='css/form-validity.css') }}">

<!--  JS  -->
<script defer src="{{ url_for('.static', filename='js/email-validity.js') }}"></script>

{% include 'includes/sidebar.html' %}
<div>
	<form id="form" method="POST" action="/settings/emails/{{ user_email.id }}" class="form-register">
		{{ form.hidden_tag() }}

		<fieldset>
			<legend>Emails</legend>
			<div class="form-container">
				<!-- Email input -->
				<div class="form-section input-control">
					{{ form.email.label(class='form-label') }}
					{% if form.email.errors %}
					{{ form.email(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.email(value=user_email.email) }}
					{% endif %}
				</div>
				<span class="email-validity-summary"></span>
			</div>

		</fieldset>
		{{ form.submit(class="button--blue") }}
	</form>
</div>

{% endblock %}

inner_air/user/templates/user/forgot.html
{% extends 'base.html' %}
{% block title %} Forgot your password {% endblock %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('.static', filename='css/form-validity.css') }}">
<script defer src="{{ url_for('.static', filename='js/email-validity.js') }}"></script>

<div>
    <form method="POST" action="" class="form-register">
        {{ form.hidden_tag() }}

        <fieldset>
            <legend>Reset your password</legend>
            <div class="form-container">
                <div class="form-section">
                    {{ form.email.label(class='form-label') }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email }}
                    {% endif %}
                </div>
                <span class="email-validity-summary"></span>
            </div>
        </fieldset>
        {{ form.submit(class="button--blue") }}
    </form>
</div>
{% endblock %}

inner_air/user/templates/user/login.html
{% extends 'base.html' %}
{% block title %} Sign-In Page {% endblock %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('.static', filename='css/form-validity.css') }}">
<script defer src="{{ url_for('.static', filename='js/email-validity.js') }}"></script>

<div>
    <form method="POST" action="" class="form-register">
        {{ form.hidden_tag() }}

        <fieldset>
            <legend>Sign in</legend>

            <!-- Email input -->
            <div class="form-container">
                <div class="form-section">
                    {{ form.email.label(class='form-label') }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email }}
                    {% endif %}
                </div>
                <span class="email-validity-summary"></span>

                <!-- Password input -->
                <div class="form-section">
                    {{ form.password.label() }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password }}
                    {% endif %}
                </div>
            </div>
        </fieldset>

        <a class="link--light" href="{{ url_for('user.forgot') }}">Forgot password?</a>

        {{ form.submit(class="button--blue") }}

        <a class="link--light" href="{{ url_for('user.register') }}">Don't have an account? Sign up</a>
    </form>
</div>
{% endblock %}

inner_air/user/templates/user/profile.html
{% extends 'base.html' %}
{% block title %} Your Profile {% endblock %}
{% block content %}

<!-- CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{{ url_for('user.static', filename='css/styles.css') }}">
<link rel="stylesheet" href="{{ url_for('.static', filename='css/form-validity.css') }}">

<!--  JS  -->
<script defer src="{{ url_for('.static', filename='js/fname-validity.js') }}"></script>
{% include 'includes/sidebar.html' %}
<div>
	<form id="form" method="POST" action="/settings/profile/{{ user_profile.id }}" class="form-register" enctype="multipart/form-data">
		{{ form.hidden_tag() }}
		<fieldset>
			<legend>Your Profile</legend>
			<div class="form-container">
				<div class="form-section">
					<div class="dl">
						<span>Profile Picture</span>
						{% if current_user.profile_picture %}
						<img src="{{ url_for('user.static', filename='img/profile_pics/' + current_user.profile_picture) }}" class="profile__img">
						{% else %}
						<img src="{{ url_for('user.static', filename='img/profile_pics/user.svg' ) }}" class="profile__img">
						{% endif %}

						<div class="dl__wrapper">
							{{ form.profile_picture(class='form-control', value=user_profile.profile_picture) }}
							<label class="form-label profile_picture dl__text--color" for="profile_picture">
								<i class="fa-solid fa-pen dl__pen--color"></i>
								Edit
							</label>
						</div>
					</div>
				</div>
			</div>

			<div class="form-container">
				<!-- First name input -->
				<div class="form-section">
					{{ form.firstname.label(class='form-label') }}
					{% if form.firstname.errors %}
					{{ form.firstname(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.firstname.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.firstname(value=user_profile.firstname) }}
					{% endif %} <br>

						<div class="tooltip">
					  		<h3 style="font-size: 0.9rem;">Enable Anonymous Mode: {{ form.anonymous_mode }}</h3>
							<span class="tooltiptext">Checking this box will prevent your user from showing on leaderboard</span>
						</div>



				</div>
				<span class="fname-validity-summary"></span>

			</div>

		</fieldset>
		{{ form.submit(class="button--blue") }}
	</form>
</div>

{% endblock %}

inner_air/user/templates/user/register.html
{% extends 'base.html' %}
{% block title %} Sign Up Page {% endblock %}
{% block content %}

<!-- CSS -->
<link rel="stylesheet" href="{{ url_for('.static', filename='css/form-validity.css') }}">

<!--  JS  -->
<script defer src="{{ url_for('.static', filename='js/fname-validity.js') }}"></script>
<script defer src="{{ url_for('.static', filename='js/email-validity.js') }}"></script>
<script defer src="{{ url_for('.static', filename='js/password-validity.js') }}"></script>
<script defer src="{{ url_for('.static', filename='js/confirm-password-validity.js') }}"></script>

<div>
	<form id="form" method="POST" action="" class="form-register">
		{{ form.hidden_tag() }}

		<fieldset>
			<legend>Create an Account</legend>
			<div class="form-container">
				<!-- First name input -->
				<div class="form-section">
					{{ form.firstname.label(class='form-label') }}
					{% if form.firstname.errors %}
					{{ form.firstname(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.firstname.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.firstname }}
					{% endif %}
				</div>
				<span class="fname-validity-summary"></span>
				

				<!-- Email input -->
				<div class="form-section input-control">
					{{ form.email.label(class='form-label') }}
					{% if form.email.errors %}
					{{ form.email(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.email }}
					{% endif %}
				</div>
				<span class="email-validity-summary"></span>

				<!-- Password input -->
				<div class="form-section">
					{{ form.password.label(class='form-label') }}
					{% if form.password.errors %}
					{{ form.password(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.password.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.password }}
					{% endif %}
				</div>
				<!-- indicator -->
				<div class="indicator">
					<span class="password-validity-weak"></span>
					<span class="password-validity-medium"></span>
					<span class="password-validity-strong"></span>
				</div>
				<span class="password-validity-summary"></span>

				<!-- Confirm password input -->
				<div class="form-section">
					{{ form.confirm_password.label(class='form-label') }}
					{% if form.confirm_password.errors %}
					{{ form.confirm_password(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.confirm_password.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.confirm_password }}
					{% endif %}
				</div>
				<span class="cpassword-validity-summary"></span>
				
			</div>

		</fieldset>
		{{ form.submit(class="button--blue") }}
		<a class="link--light" href="{{ url_for('user.login') }}">Already have an account? Sign in</a>
	</form>
</div>

{% endblock %}

inner_air/user/templates/user/reset_password.html
{% extends 'base.html' %}
{% block title %} Forgot Password {% endblock %}
{% block content %}

<!-- CSS -->
<link rel="stylesheet" href="{{ url_for('.static', filename='css/form-validity.css') }}">

<!-- JS -->
<script defer src="{{ url_for('.static', filename='js/password-validity.js') }}"></script>
<script defer src="{{ url_for('.static', filename='js/confirm-password-validity.js') }}"></script>

<div>
    <form method="POST" action="" class="form-register">
        {{ form.hidden_tag() }}

        <fieldset>
            <legend>Forgot Your Password?</legend>
            <div class="form-container">
                <!-- Password input -->
                <div class="form-section">
                    {{ form.password.label(class='form-label') }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password }}
                    {% endif %}
                </div>
                <!-- indicator -->
				<div class="indicator">
					<span class="password-validity-weak"></span>
					<span class="password-validity-medium"></span>
					<span class="password-validity-strong"></span>
				</div>
				<span class="password-validity-summary"></span>

                <!-- Confirm password input -->
                <div class="form-section">
                    {{ form.confirm_password.label(class='form-label') }}
                    {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.confirm_password }}
                    {% endif %}
                </div>
                <span class="cpassword-validity-summary"></span>

            </div>
        </fieldset>
        {{ form.submit(class="button--blue") }}
    </form>
</div>
{% endblock %}

inner_air/user/templates/user/reset_request.html
<p>Click on the following link to reset your password:</p>
<p><a href="{{ reset_url }}">{{ reset_url }}</a></p>

inner_air/user/templates/user/unconfirmed.html
{% extends 'base.html' %}
{% block title %}
verify email
{% endblock %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('.static', filename='css/user.css') }}">
<script defer src="{{ url_for('.static', filename='js/app.js')}}"></script>

<div id='modal-1' class='modal'>
    <div class='modal-content'>
        <!-- Modal header -->
        <div class="modal-header">
            <h2>Welcome</h2>
        </div>
        <hr>
        <!-- Modal body -->
        <div class="modal-body">
            <p>
                You have not confirmed your account. Please check you (and your spam folder) - you should have received
                an
                email with a confirmation link.
            </p>
        </div>
        <!-- Modal footer -->
        <div class="modal-footer">
            <span>Didn't get the email?</span>
            <p>
                <a class="button--blue" href="{{ url_for('user.resend_confirmation') }}">resend</a>
            </p>
        </div>
    </div>
</div>

{% endblock %}