inner_air/main/routes.py
from flask import Blueprint, render_template

main_bp = Blueprint(
    'main', __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/%s' % __name__
)


@main_bp.route('/')
@main_bp.route('/home')
def home():
    return render_template('main/index.html')


@main_bp.route('/about')
def about():
    return render_template('about.html')

inner_air/main/templates/about.html
{% extends 'base.html' %}
{% block title %}
Inner Air
{% endblock %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('main.static', filename='css/about.css') }}">

<div class="about">
    <div class="box">
        <img src="{{ url_for('main.static', filename='img/about/jade.jpg') }}" class="about_img">
        <h2>Jade</h2>
        <p>Jade is a human who enjoys eating food and drinking water.</p>
    </div>
    <div class="box">
        <img src="{{ url_for('main.static', filename='img/about/andrew.jpg') }}" class="about_img">
        <h2>Andrew</h2>
        <p>Andrew is a person who exists and enjoys breathing oxygen and walking with his human legs.</p>
    </div>
    <div class="box">
        <img src="{{ url_for('main.static', filename='img/about/chris1.jpg') }}" class="about_img">
        <h2>Christian</h2>
        <p>Christian is a dude from N.C.</p>
    </div>
    <div class="box">
        <img src="{{ url_for('main.static', filename='img/about/karina.jpg') }}" class="about_img">
        <h2>Karina</h2>
        <p>Will come to your house and sort everything by color.</p>
    </div>
    <div class="box">
        <img src="{{ url_for('main.static', filename='img/about/jose.jpg') }}" class="about_img">
        <h2>Jose</h2>
        <p>Jose is a ¯\_(ツ)_/¯</p>
    </div>
</div>

<section class="contact">
    <h1>Questions?</h1>
    <h2>Contact us at admin@inner-air.com</h2>
</section>

{% endblock %}

inner_air/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<!-- HEAD -->

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    <link rel="icon" href="{{ url_for('main.static', filename='ico/inner-air.ico')}}">

    <!-- CSS -->
    <link rel="stylesheet" href="{{ url_for('main.static', filename='css/base.css')}}">
</head>

<!-- BODY -->

<body>

    {% include 'navigation.html' %}

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

    <!-- Flash messages to display upon submission for Registration and Login forms-->
    <div id="hide-me" class="pop-in">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert--{{ category }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>

</body>

</html>

inner_air/main/templates/main/index.html
{% extends 'base.html' %}
{% block title %}
Inner Air
{% endblock %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('main.static', filename='css/index.css')}}">

<div class="wrapper">
    <div class="top">
        <h1>Welcome to</h1>
        <img class="logo" src="{{ url_for('main.static', filename='img/logo_text.svg') }}"></img>
        <h3>Your Personal Breathing Exercise Companion</h3>
        <section class="description">
            <h2 class="desc-header">Wondering why there's an entire site for breathing?</h2>
            <p class="desc-text" class="intro">That is a great question. Here you will find a multitude of exercises,
                techniques and information regarding breathing. Let us tell you why
                you should take a special interest in how something you do everyday
                can do more than just keep you alive.</p>
        </section>

    </div>

    <section class="sec-boxes">
        <article class="box">
            <h1 class="box-header" id="exercise">Exercise</h1>
            <img class="imgs" id="exercise" src="{{ url_for('main.static', filename='img/Exercise.png') }}"></img>
            <p class="box-description">
                Proper breathing techniques during exercise can help you breathe more efficiently,
                allowing you to take in more oxygen and remove more carbon dioxide.
                This can help you maintain physical activity for longer periods of time,
                improve your cardiovascular health and increase your endurance.
                <br>
                <br>
                Along with that, they help to maximize the efficiency of your movements,
                allowing you to perform exercises with greater ease and accuracy.
                This can improve your overall physical performance, leading to better results in your workouts.
            </p>
            <a href ="https://www.lung.org/lung-health-diseases/wellness/exercise-and-lung-health" target ="_blank" class="button button--red--dynamic"> Learn More</a>
        </article>

        <article class="box">
            <h1 class="box-header" id="meditate">Meditate</h1>
            <img class="imgs" id="meditate" src="{{ url_for('main.static', filename='img/Meditation.png') }}"></img>
            <p class="box-description">Correctly learning to breathe can be an important part
                of your whole body, not just your lungs. Here you will find
                breathing techniques designed to help reduce stress and
                provide other positive benefits such as lowering blood
                pressure and improving sleep quality.
                <br>
                <br>
                Focusing on the breath can help you become more aware of your thoughts, feelings, and physical
                sensations.
                This can help you better understand yourself and develop greater self-awareness.</p>
            <a href="https://www.mayoclinic.org/tests-procedures/meditation/in-depth/meditation/art-20045858" target="blank" class="button button--green--dynamic">Learn More</a>
        </article>

        <article class="box">
            <h1 class="box-header" id="relaxation">Relaxation</h1>
            <img class="imgs" id="relaxation" src="{{ url_for('main.static', filename='img/Relaxation.png') }}"></img>
            <p class="box-description">Mindful breathing techniques can have a positive effect on your mind
                as well as the physical benefits mentioned previously.
                Breathing exercises can help reduce the amount of cortisol (a stress hormone) in your body,
                leading to a decrease in feelings of stress and anxiety.
                <br>
                <br>
                This can help you feel more relaxed and centered during your workouts,
                making it easier to stay motivated and focused.</p>
            <a href="https://www.scientificamerican.com/article/proper-breathing-brings-better-health/" target="_blank" class="button button--blue--dynamic">Learn More</a>
        </article>

    </section>

</div>

{% endblock %}

inner_air/main/templates/navigation.html
<header>
	<link rel="stylesheet" href="{{ url_for('main.static', filename='css/header_nav.css')}}">

	<nav class="header-container">
		<a href="{{ url_for('main.home') }}">
			<img src=" {{ url_for('main.static', filename='img/logo_text.svg' ) }}" class="logo"></img>
		</a>

		<div class="navigation-container">
			{% if not current_user.is_confirmed %}
			<p id = "quote"> GET MOTIVATED </p>
			{% endif %}
			<div class="navigation">
				{% if current_user.is_confirmed %}
					{% if 'exercises' in request.path %}
					<a class="nav-link active" href="{{ url_for('exercises.exercises') }}">EXERCISES</a>
					{% else %}
					<a class="nav-link" href="{{ url_for('exercises.exercises') }}">EXERCISES</a>
					{% endif %}

					{% if 'profile' in request.path %}
					<a class="nav-link active" href="{{ url_for('profile.profile') }}">Profile</a>
					{% else %}
					<a class="nav-link" href="{{ url_for('profile.profile') }}">Profile</a>
					{% endif %}

					{% if 'leaderboard' in request.path %}
					<a class="nav-link active" href="{{ url_for('leaderboard.leaderboard') }}">Leaderboard</a>
					{% else %}
					<a class="nav-link" href="{{ url_for('leaderboard.leaderboard') }}">Leaderboard</a>
					{% endif %}

					{% if 'about' in request.path %}
					<a class="nav-link active" href="{{ url_for('main.about') }}">About</a>
					{% else %}
					<a class="nav-link" href="{{ url_for('main.about') }}">About</a>
					{% endif %}
				{% endif %}
			</div>
		</div>

		<div class="buttons">
			{% if current_user.is_admin %}
			<a class="button--red--dynamic" href="{{ url_for('admin.admin') }}">ADMIN</a>
			{% endif %}
			{% if current_user.is_authenticated %}
			{% if not current_user.is_confirmed %}
			<a class="button--green--dynamic" href="{{ url_for('profile.profile') }}">VERIFY</a>
			{% else %}
			<a class="button--blue--dynamic" href="{{ url_for('user.profile', id=current_user.id) }}">SETTINGS</a>
			{% endif %}
			<a class="button--red--dynamic" href="{{ url_for('user.logout') }}">SIGN OUT</a>
			{% else %}
			<a class="button--red--dynamic" href="{{ url_for('user.login') }}">SIGN IN</a>
			<a class="button--blue--dynamic" href="{{ url_for('user.register') }}">SIGN UP</a>
			{% endif %}
		</div>
	</nav>
	<script src="{{ url_for('main.static', filename='js/index_quote.js') }}"></script>
</header>