inner_air/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Email


class UserRecordForm(FlaskForm):
    firstname = StringField(
        label='First Name',
        validators=[DataRequired(), Length(min=3, max=20)],
        render_kw={"placeholder": "First Name"}
    )
    email = StringField(
        label='Email',
        validators=[DataRequired(), Email()],
        render_kw={'placeholder': 'Email'}
    )
    submit = SubmitField(
        label='Update Record'
    )

inner_air/admin/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, abort
from flask_login import login_required, current_user

from inner_air import db
from inner_air.admin.forms import UserRecordForm
from inner_air.models import User
from inner_air.utils.decorators import check_confirmed

admin_bp = Blueprint(
    'admin', __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/%s' % __name__
)


@admin_bp.route('/admin', methods=['GET', 'POST'])
@login_required
@check_confirmed
def admin():
    users = User.query.all()
    if not current_user.is_admin:
        abort(403)

    return render_template('admin/admin.html', users=users)


@admin_bp.route('/admin/update/<int:id>', methods=['GET', 'POST'])
@login_required
@check_confirmed
def update(id):
    form = UserRecordForm()
    user = db.session.query(User).get_or_404(id)

    if not current_user.is_admin:
        abort(403)

    if form.validate_on_submit():
        user.firstname = request.form['firstname']
        user.email = request.form['email']

        if user.is_confirmed:
            user.is_confirmed = False

        try:
            db.session.commit()
            flash('User Updated Successfully!', category='success')
            return render_template('includes/update.html', form=form, user=user)
        except Exception:
            flash('An error occurred...try again.', category='danger')
            return render_template('includes/update.html', form=form, user=user)
    else:
        return render_template('includes/update.html', form=form, user=user)


@admin_bp.route('/admin/delete/<int:id>', methods=['GET', 'POST'])
@login_required
@check_confirmed
def delete(id):
    user = db.session.query(User).get_or_404(id)

    if not current_user.is_admin:
        abort(403)

    try:
        db.session.delete(user)
        db.session.commit()

        flash('User deleted successfully!', category='success')
        user = User.query.order_by(User.created_time)

        return redirect(url_for('admin.admin'))
    except Exception:
        flash('An error occurred...try again.', category='danger')
        return redirect(url_for('admin.admin'))

inner_air/admin/templates/includes/update.html
{% extends 'base.html' %}
{% block title %}  Update Record {% endblock %}
{% block content %}

<!-- CSS -->
<link rel="stylesheet" href="{{ url_for('user.static', filename='css/form-validity.css') }}">
<link rel="stylesheet" href="{{ url_for('user.static', filename='css/user.css') }}">

<!--  JS  -->
<script defer src="{{ url_for('user.static', filename='js/fname-validity.js') }}"></script>
<script defer src="{{ url_for('user.static', filename='js/email-validity.js') }}"></script>
<script defer src="{{ url_for('user.static', filename='js/password-validity.js') }}"></script>
<script defer src="{{ url_for('user.static', filename='js/confirm-password-validity.js') }}"></script>

<div>
	<form id="form" method="POST" action="/admin/update/{{ user.id }}" class="form-register">
		{{ form.hidden_tag() }}

		<fieldset>
			<legend>Update {{ user.firstname }}'s Record </legend>
			<div class="form-container">
				<div class="form-section">
					<div class="dl">
						{% if user.profile_picture %}
						<img src="{{ url_for('user.static', filename='img/profile_pics/' + user.profile_picture) }}" class="profile__img">
						{% else %}
						<img src="{{ url_for('user.static', filename='img/profile_pics/def_pic.png' ) }}" class="profile__img">
						{% endif %}
					</div>
				</div>
			</div>

			<div class="form-container">
				<!-- First name input -->
				<div class="form-section">
					{{ form.firstname.label(class='form-label') }}
					{% if form.firstname.errors %}
					{{ form.firstname(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.firstname.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.firstname(value=user.firstname) }}
					{% endif %}
				</div>
				<span class="fname-validity-summary"></span>


				<!-- Email input -->
				<div class="form-section input-control">
					{{ form.email.label(class='form-label') }}
					{% if form.email.errors %}
					{{ form.email(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.email(value=user.email) }}
					{% endif %}
				</div>
				<span class="email-validity-summary"></span>
			</div>

		</fieldset>

		{% if user.is_confirmed %}
			{{ form.submit(class="button--blue") }}
		{% else %}
			<div class="" style="display: flex; justify-content: space-between;">
				{{ form.submit(class="button--blue", style="font-size: 10px;") }}
				<a href="{{ url_for('admin.delete', id=user.id) }}" class="button--red--dynamic" style="font-size: 10px;">
					DELETE RECORD
				</a>
			</div>
		{% endif %}
	</form>
</div>

{% endblock %}

inner_air/admin/templates/includes/user/user_list.html
	 <div class="container-fluid overlay min-vh-100 py-5 mt-5">
         <div class="wrapper">
             {% if current_user.profile_picture %}
             <img src="{{ url_for('user.static', filename='img/profile_pics/' + current_user.profile_picture) }}" class="img">
             {% else %}
             <img src="{{ url_for('user.static', filename='img/profile_pics/user.svg' ) }}" class="img">
             {% endif %}
             <h1>Welcome, {{ current_user.firstname }} </h1>
         </div>

        <h2 class="text-center">Users</h2>
        <table class="table table-hover table-dark">
            <!-- User Model -->
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">ID</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Password</th>
                    <th scope="col">Created Time</th>
                    <th scope="col">Confirmed</th>
                    <th scope="col">Confirmed on</th>
                    <th scope="col">Consecutive Days</th>
                    <th scope="col">Last login</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>
                        <div class="td-wrapper">
                            {% if user.is_confirmed %}
                                <a href="{{ url_for('admin.update', id=user.id) }}">
                                    <i class="fa-solid fa-pen fa-pen--hover"></i>
                                </a>
                            {% else %}
                                <a href="{{ url_for('admin.update', id=user.id) }}">
                                    <i class="fa-solid fa-pen fa-pen--hover"></i>
                                </a>
                                <a href="{{ url_for('admin.delete', id=user.id) }}">
                                    <i class="fa-sharp fa-solid fa-trash fa-trash--hover"></i>
                                </a>
                            {% endif %}
                        </div>
                    </td>
                    <td>{{ user.id }}</td>
                    <td>{{ user.firstname }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        <div class="div">
                            {{ user.password }}
                        </div>
                    </td>
                    <td>
                        <div class="div">
                            {{ user.created_time }}
                        </div>
                    </td>
                    <td class="confirmed">
                        {% if user.is_confirmed %}
                            <i class="fa-solid fa-circle-check fa-circle-check--color"></i>
                        {% else %}
                            <i class="fa-solid fa-circle-exclamation fa-circle-exclamation--color"></i>
                        {% endif %}
                    </td>
                    <td class="">
                        <div class="div">
                            {{ user.confirmed_on }}
                        </div>
                    </td>
                    <td>{{ user.consecutive_days }}</td>
                    <td>
                        <div class="div">
                            {{ user.last_login }}
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>