inner_air/exercises/forms.py
from flask_wtf import FlaskForm
from wtforms import RadioField, SubmitField


class RateEx(FlaskForm):
    RateField = RadioField(label='Rate this Exercise',
                           choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])
    submit = SubmitField(
        label='Submit Rating'
    )

inner_air/exercises/routes.py
import flask_login
from flask import Blueprint, request, render_template, jsonify
from flask_login import login_required

from inner_air import db
from inner_air.exercises.forms import RateEx
from inner_air.models import Favorites, Exercise, UserRating, Statistics
from inner_air.utils.decorators import check_confirmed

exercises_bp = Blueprint(
    'exercises', __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/%s' % __name__
)


@exercises_bp.route('/exercises/', methods=['GET', 'POST'])
@login_required
@check_confirmed
def exercises():
    if request.method == 'POST':

        # Check if the request form contains "favoriteButton" key
        if "favoriteButton" in request.form:
            # Retrieve user and exercise IDs from the request form
            currentUser = request.form['user_id']
            currentExercise = request.form['exercise_id']
            # Check if the current combination of user and exercise IDs is already in the Favorites table
            if db.session.query(Favorites).filter(Favorites.user_id == currentUser).filter(
                    Favorites.exercise_id == currentExercise).first() is None:
                db.session.add(Favorites(user_id=currentUser,
                                         exercise_id=currentExercise))
                db.session.commit()

        # Check if the request form contains "favoriteButtonRemove" key
        elif "favoriteButtonRemove" in request.form:
            # Retrieve user and exercise IDs from the request for
            currentUser = request.form['user_id']
            currentExercise = request.form['exercise_id']
            # Check if the current combination of user and exercise IDs is in the Favorites table
            if db.session.query(Favorites).filter(Favorites.user_id == currentUser).filter(
                    Favorites.exercise_id == currentExercise).first() is not None:
                toDelete = db.session.query(Favorites).filter(Favorites.user_id == currentUser).filter(
                    Favorites.exercise_id == currentExercise).first()
                db.session.delete(toDelete)
                db.session.commit()
        else:
            pass
    # Retrieve all entries from the Exercise and Favorites tables
    exercise_list = Exercise.query.all()
    favorite_list = Favorites.query.all()

    # Define a function to show the exercises that the current user has in the Favorites table
    def showFav():
        listOfExerciseCurrentUserHasInFavorites = []
        for favorite in favorite_list:
            if favorite.as_dict()['user_id'] == flask_login.current_user.id:
                listOfExerciseCurrentUserHasInFavorites.append(
                    favorite.as_dict()['exercise_id'])
        return listOfExerciseCurrentUserHasInFavorites

    return render_template('exercises/exercises.html', exercises=exercise_list, favorites=favorite_list,
                           showFavAdd=showFav())


"""
    first_or_404() - returns the first result of the query or HTTP 404 Error.

    https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/api/#module-flask_sqlalchemy.pagination:~:text=Session%5D)%20%E2%80%93-,first_or_404,-(description%3D
"""


# Exercise route - intent is to generate exercise pages dynamically via data in a database. This way if we wanted to update by adding new exercises we can make changes to db.

@exercises_bp.route('/exercises/<exid>/', methods=['GET', 'POST'])
@login_required
@check_confirmed
def get_exercise_id(exid):
    # Update cumulative ratings on page load
    def updateRatings():
        all_ex_data = db.session.query(
            UserRating).filter_by(exercise_id=exid).all()
        all_ex_data_count = len(all_ex_data)
        all_ex_data_total = 0
        if all_ex_data_count > 0:
            for i in all_ex_data:
                all_ex_data_total += i.user_rating
            cumulateData = all_ex_data_total / all_ex_data_count
            db.session.query(Exercise).filter_by(
                id=exid).first().update_cumulative_rating(cumulateData)
            db.session.commit()

    updateRatings()

    if exid.upper() == "DEMO":
        this_exercise = db.session.query(
            Exercise).filter_by(exercise_name="Demo Exercise").first_or_404()
        exid = this_exercise.id
    else:
        this_exercise = db.session.query(
            Exercise).filter_by(id=exid).first_or_404()

    form = RateEx()
    if request.method == 'POST':
        if 'breathHoldTotalSeconds' in request.form:
            db.session.add(Statistics(exercise_id=exid, user_id=flask_login.current_user.id,
                                      hold_length=(float(request.form['breathHoldTotalSeconds'])) / 100))
            db.session.commit()
        if 'exerciseComplete' in request.form:
            db.session.add(Statistics(exercise_id=exid, user_id=flask_login.current_user.id))
            db.session.commit()

    if form.validate():
        # Check if user has rated this before
        usersRating = db.session.query(UserRating).filter_by(
            user_id=flask_login.current_user.id, exercise_id=exid).first()
        if usersRating is None:
            usersRating = (UserRating(user_rating=int(
                form.RateField.data), user_id=flask_login.current_user.id, exercise_id=exid))
            db.session.add(usersRating)
        else:
            usersRating.update_rating(int(form.RateField.data))
        db.session.commit()
        updateRatings()
    if this_exercise.exercise_name == "Control Pause" or this_exercise.exercise_name == "Mini Breath Holds":
        return render_template('exercises/exerciseBreathHold.html', this_exercise=this_exercise, form=form)
    else:
        return render_template('exercises/exerciseAnimation.html', this_exercise=this_exercise, form=form)


"""
    Sends data using AJAX request to a javascript
"""


@exercises_bp.route('/exercises/<exid>/animation.data', methods=['GET'])
@login_required
@check_confirmed
def send_animation_data(exid):
    if exid.upper() == "DEMO":
        exercise = db.session.query(
            Exercise).filter_by(exercise_name="Demo Exercise").first_or_404()
    else:
        exercise = db.session.query(Exercise).filter_by(id=exid).first_or_404()

    # Data used for animations
    animation_data = {
        "inhale_time": exercise.exercise_inhale,
        "inhale_hold": exercise.exercise_inhale_pause,
        "exhale_time": exercise.exercise_exhale,
        "exhale_hold": exercise.exercise_exhale_pause,
        "cycle_count": exercise.exercise_length,
        "current_user": flask_login.current_user.id,
        "current_exercise": exercise.id
    }

    # Send data in a json format
    return jsonify(animation_data)

inner_air/exercises/templates/exercises/exerciseAnimation.html
{% extends 'base.html' %}
{% block title %}
Exercises
{% endblock %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('exercises.static', filename='css/feather_breathing.css')}}">
<link rel="stylesheet" href="{{ url_for('exercises.static', filename='css/exercise_page.css')}}">

<div class="exercise-container">
    <h1 class="exe-name">{{ this_exercise.exercise_name }} - {{ "%.2f"|format(this_exercise.cumulative_rating|default(5.0, true)) }}  ★
    </h1>
    <h3 class="exe-description">{{ this_exercise.exercise_description }}</h3>
    <p class="exe-instructions">{{ this_exercise.exercise_instructions }}</p>

    <div class="breathing-animation-container">
        <h1 id="timer">Waiting for exercise to start</h1>
        <div class="animation-scope"> <img id="feather" class="float-object top"
                src="{{ url_for('exercises.static', filename='img/feather.svg') }}"></img>
        </div>
        <button id="start-button" class="button--green">Start</button>
        <script src="{{ url_for('exercises.static', filename='js/breathing-animation.js') }}"></script>
    </div>

    <div class="exe-rating-tool">
        <form action="" method="POST" class="form-rate">
            {{ form.hidden_tag() }}
            {{ form.RateField.label }}

            {% for subfield in form.RateField %}
            <tr>
                <td>{{ subfield }}</td>
                <td>{{ subfield.label }}</td>
            </tr>
            {% endfor %}
            {{ form.submit(class="button--red") }}

        </form>
    </div>
</div>
{% endblock %}

inner_air/exercises/templates/exercises/exerciseBreathHold.html
{% extends 'base.html' %}
{% block title %}
Exercises
{% endblock %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('exercises.static', filename='css/feather_breathing.css')}}">
<link rel="stylesheet" href="{{ url_for('exercises.static', filename='css/exercise_page.css')}}">
<link rel="stylesheet" href="{{ url_for('exercises.static', filename='css/stopwatch.css')}}">


<div class="stopwatch-container">
    <h1 class="exe-name">{{ this_exercise.exercise_name }} - {{ "%.2f"|format(this_exercise.cumulative_rating|default(5.0, true)) }} ★</h1>
    <h3 class="exe-description">{{ this_exercise.exercise_description }}</h3>
    <p class="exe-instructions">{{ this_exercise.exercise_instructions }}</p>
    <div class="timer">
        <div id="time">
            <div class="mark">
                <span class="digits" id="min">00</span>
                <span class="text">Minutes</span>
            </div>
            <div class="mark">
                <span class="digits" id="sec">00</span>
                <span class="text">Seconds</span>
            </div>
            <div class="mark">
                <span class="digits" id="count">00</span>
            </div>
            
        </div>

        <div class="buttons" id="buttons">
            <button class="button--green--dynamic" id="start"> Start </button>
            <button class="button--red--dynamic" id="stop" onClick="show()"> Stop </button>
            <button class="button--blue--dynamic" id="reset" onClick="hide()"> Reset </button>

            <form action="" method="post">
                <input type="hidden" id="breathHoldTotalSeconds" name="breathHoldTotalSeconds" value="00">
                <button hidden class="button--dynamic" id="submitHold"> Submit </button>
            </form>

        </div>

        <script src="{{ url_for('exercises.static', filename='js/Stopwatch_script.js') }}"></script>

    </div>
    <div class="ExerciseRatingTool">
        <form method="POST" class="form-rate">
            {{ form.hidden_tag() }}
            {{ form.RateField.label }}
            {% for subfield in form.RateField %}
            <tr>
                <td>{{ subfield }}</td>
                <td>{{ subfield.label }}</td>
            </tr>
            {% endfor %}
            {{ form.submit(class="button--red") }}

        </form>
    </div>
</div>
{% endblock %}

inner_air/exercises/templates/exercises/exercises.html
{% extends 'base.html' %}
{% block title %}
Exercises
{% endblock %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('exercises.static', filename='css/exercise_list.css')}}">


<h1 class="list-heading">Choose your exercise</h1>

<div class="list-container">
    <ul class="list">
        {% for exercise in exercises %}
        <li class="plate">
            <section class="upper">
                <label for={{ exercise.id }} class="name">
                    <a class="name" href="{{ url_for('exercises.get_exercise_id', exid=exercise.id) }}"
                        target="_self">{{ exercise.exercise_name }} - {{ "%.2f"|format(exercise.cumulative_rating|default(5.0, true)) }} ★</a>
                </label>
                <span id="favorite-button">
                    {% if exercise.id not in showFavAdd %}
                    <form method="post">
                        <input name="exercise_id" class="invs" type="hidden" value="{{ exercise.id }}"> </input>
                        <input name="user_id" class="invs" type="hidden" value="{{ current_user.id }}"> </input>
                        <button type="submit" name="favoriteButton" class="button--green">🤍</button>
                    </form>
                    {% endif %}
                    {% if exercise.id in showFavAdd %}
                    <form method="post">
                        <input name="exercise_id" class="invs" type="hidden" value="{{ exercise.id }}"> </input>
                        <input name="user_id" class="invs" type="hidden" value="{{ current_user.id }}"> </input>
                        <button type="submit" name="favoriteButtonRemove" class="button--red">🖤</button>
                    </form>
                    {% endif %}
                </span>
            </section>

            <p class="description">
                {{ exercise.exercise_description }}
            </p>
        </li>
        {% endfor %}
    </ul>

    <script src="{{ url_for('exercises.static', filename='js/expand_list_element.js') }}"></script>
</div>
{% endblock %}